services:
  bunkerweb:
    extends:
      file: compose-bunkerweb.yml
      service: bunkerweb
  
  bw-scheduler:
    extends: 
      file: compose-bunkerweb.yml
      service: bw-scheduler
    depends_on:
      - bunkerweb

  bw-docker:
    extends:
      file: compose-bunkerweb.yml
      service: bw-docker

  bw-autoconf:
    extends:
      file: compose-bunkerweb.yml
      service: bw-autoconf
    depends_on:
      - bunkerweb
      - bw-docker

  bw-ui:
    extends:
      file: compose-bunkerweb.yml
      service: bw-ui
    depends_on:
      - bunkerweb

  bw-db:
    extends:
      file: compose-bunkerweb.yml
      service: bw-db
    depends_on:
      - bunkerweb

  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - ./CTFd:/opt/CTFd:ro
    networks:
      - bw-services
      - ctfd-internal
    labels:
      - "bunkerweb.IS_DRAFT=no"
      - "bunkerweb.SERVER_NAME=ctfd.demo.lan"
      - "bunkerweb.USE_TEMPLATE=low"
      - "bunkerweb.BAD_BEHAVIOR_THRESHOLD=30"
      - "bunkerweb.BAD_BEHAVIOR_BAN_TIME=3600"
      - "bunkerweb.USE_BLACKLIST=no"
      - "bunkerweb.USE_CORS=yes"
      - "bunkerweb.CORS_ALLOW_ORIGIN=*"
      - "bunkerweb.BLACKLIST_COUNTRY=US"
      - "bunkerweb.USE_DNSBL=no"
      - "bunkerweb.INTERCEPTED_ERROR_CODES=400 404 405 413 429 500 501 502 503 504"
      - "bunkerweb.KEEP_UPSTREAM_HEADERS=*"
      - "bunkerweb.CONTENT_SECURITY_POLICY="
      - "bunkerweb.REFERRER_POLICY=no-referrer-when-downgrade"
      - "bunkerweb.PERMISSIONS_POLICY="
      - "bunkerweb.COOKIE_FLAGS=* SameSite=Lax"
      - "bunkerweb.LIMIT_CONN_MAX_HTTP1=25"
      - "bunkerweb.LIMIT_CONN_MAX_HTTP2=200"
      - "bunkerweb.LIMIT_CONN_MAX_HTTP3=200"
      - "bunkerweb.LIMIT_REQ_RATE=5r/s"
      - "bunkerweb.ALLOWED_METHODS=GET|POST"
      - "bunkerweb.MAX_CLIENT_SIZE=100m"
      - "bunkerweb.USE_MODSECURITY=no"
      - "bunkerweb.USE_MODSECURITY_CRS_PLUGINS=no"
      - "bunkerweb.USE_REVERSE_PROXY=yes"
      - "bunkerweb.REVERSE_PROXY_HOST=http://ctfdwaf-ctfd-1:8000"
      - "bunkerweb.USE_UI=yes"

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        - ctfd-internal
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        - ctfd-internal

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24 # Make sure to set the correct IP range so the scheduler can send the configuration to the instance
  bw-services:
    name: bw-services
  bw-db:
    name: bw-db
  ctfd-internal:
    name: ctfd-internal
    internal: true
  bw-docker:
    name: bw-docker

volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  bw-data:
  bw-storage:
