services:
  bunkerweb:
    extends:
      file: compose-bunkerweb.yml
      service: bunkerweb
  
  bw-scheduler:
    extends: 
      file: compose-bunkerweb.yml
      service: bw-scheduler
    depends_on:
      - bunkerweb

  bw-ui:
    extends:
      file: compose-bunkerweb.yml
      service: bw-ui
    depends_on:
      - bunkerweb

  bw-db:
    extends:
      file: compose-bunkerweb.yml
      service: bw-db
    depends_on:
      - bunkerweb

  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - ./CTFd:/opt/CTFd:ro
    networks:
      - bw-services

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24 # Make sure to set the correct IP range so the scheduler can send the configuration to the instance
  bw-services:
    name: bw-services
  bw-db:
    name: bw-db

volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  bw-data:
  bw-storage:
